name = "quiz-front-poc"
compatibility_date = "2023-12-01"

# ビルド設定
pages_build_output_dir = "./dist" # ビルド出力ディレクトリ（pages_build_output_dirが最新の書き方）

# 環境設定
[site]
bucket = "./dist" # 静的ファイルが置かれるディレクトリ

# 環境変数設定
[vars]
NODE_ENV = "production"

# 本番環境設定
[env.production]
name = "quiz-front-poc"
route = ""
workers_dev = false

# 開発環境設定
[env.development]
name = "quiz-front-poc-dev"
workers_dev = true

# プレビュー環境用の設定（PR用など）
[env.preview]
name = "quiz-front-poc-preview"
workers_dev = true
